#!/usr/bin/env python

import pulsectl
import subprocess

def get_volume():
    mute = subprocess.run(['pamixer', '--get-mute'], capture_output=True).stdout.decode("utf-8").rstrip()
    if mute == 'true':
        print('MUTE', flush=True)
    else:
        volume = subprocess.run(['pamixer', '--get-volume'], capture_output=True).stdout.decode("utf-8").rstrip()
        print(volume, flush=True)

def stop_loop(_):
    raise pulsectl.PulseLoopStop

with pulsectl.Pulse('event-printer') as pulse:
    get_volume()
    while True:
        pulse.event_mask_set('all')
        pulse.event_callback_set(stop_loop)
        pulse.event_listen()
        get_volume()


