#!/usr/bin/env python

import pulsectl
import subprocess

def get_volume():
    mute = subprocess.run(['pamixer', '--get-mute'], capture_output=True).stdout.decode("utf-8").rstrip()
    if mute == 'true':
        subprocess.run(['echo', 'MUTE'])
    else:
        volume = subprocess.run(['pamixer', '--get-volume'], capture_output=True).stdout.decode("utf-8").rstrip()
        subprocess.run(['echo', volume])

def stop_loop(_):
    raise pulsectl.PulseLoopStop

if __name__ == "__main__":
    get_volume()
    with pulsectl.Pulse('event-printer') as pulse:
        while True:
            pulse.event_mask_set('client')
            pulse.event_callback_set(stop_loop)
            pulse.event_listen()
            get_volume()


